In [3]:
import pandas as pd 
import numpy as np
import glob
import os

In [29]:
def get_raw_data(directory):

    csv_files = glob.glob(os.path.join(directory, "*.csv"))
    xlsx_files = glob.glob(os.path.join(directory, "*.xlsx"))
    final_df = pd.DataFrame(columns=['model_year', 'manufacturer_name', 'vehicle_model', 'displacement', 'num_cylinders', \
                            'city_FE', 'hwy_FE', 'combine_FE', 'drive_system','fuel_type', 'vehicle_type'])
    for csv_item in csv_files:
        file_name = csv_item[32:] # Get the file name of each path
        if int(file_name[:4]) in [2002, 2003, 2004, 2005, 2007, 2008, 2009]:
            df = pd.read_csv(csv_item, usecols = [0,1,2,3,4,6,8,9,10,14])
            df = df.iloc[:, [1,2,3,4,6,7,8,5,9,0]]
            new_col = pd.Series([int(file_name[:4])]*len(df))
            df.insert(0, 'model_year', new_col)
            df.columns = final_df.columns.tolist()
            final_df = pd.concat([final_df, df], ignore_index=True)
        else:
            df = pd.read_csv(csv_item, usecols = [0,1,2,3,4,6,7,8,9,13])
            df = df.iloc[:, [1,2,3,4,6,7,8,5,9,0]]
            new_col = pd.Series([int(file_name[:4])]*len(df))
            df.insert(0, 'model_year', new_col)
            df.columns = final_df.columns.tolist()
            final_df = pd.concat([final_df, df], ignore_index=True)

    for xlsx_item in xlsx_files:
        file_name = xlsx_item[32:] # Get the file name of each path
        if int(file_name[:4]) in list(range(2013,2026)):
            df = pd.read_excel(xlsx_item, sheet_name=0, usecols = [0,2,3,6,7,9,10,11,27,33,69])
            df.columns = final_df.columns.tolist()
            final_df = pd.concat([final_df, df], ignore_index=True)
        else:
            df = pd.read_excel(xlsx_item, sheet_name=0, usecols = [0,2,3,6,7,9,10,11,27,33,66])
            df.columns = final_df.columns.tolist()
            final_df = pd.concat([final_df, df], ignore_index=True)
    
    return final_df
    
# Find all xlsx and CSV files in the directory
directory = "../fuel_economy_data/extract_to/"  
raw_data = get_raw_data(directory)
raw_data.head()

/var/folders/rh/5tkty3715h119sm4y35zw4dr0000gn/T/ipykernel_60228/1426218314.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, df], ignore_index=True)

,model_year,manufacturer_name,vehicle_model,displacement,num_cylinders,city_FE,hwy_FE,combine_FE,drive_system,fuel_type,vehicle_type
0,2007,ASTON MARTIN,V8 VANTAGE,4.3,8.0,14.0,20.0,16.0,R,P,TWO SEATERS
1,2007,ASTON MARTIN,V8 VANTAGE ASM,4.3,8.0,15.0,21.0,17.0,R,P,TWO SEATERS
2,2007,BMW,Z4 3.0I,3.0,6.0,20.0,30.0,24.0,R,P,TWO SEATERS
3,2007,BMW,Z4 3.0I,3.0,6.0,21.0,30.0,24.0,R,P,TWO SEATERS
4,2007,BMW,Z4 3.0SI,3.0,6.0,20.0,30.0,24.0,R,P,TWO SEATERS

In [ ]:
raw_data.to_csv("../fuel_economy_data/merge_raw_data.csv", index=False)

,Model Year,Division,Carline,Eng Displ,# Cyl,City FE (Guide) - Conventional Fuel,Hwy FE (Guide) - Conventional Fuel,Comb FE (Guide) - Conventional Fuel,Drive Sys,Fuel Usage Desc - Conventional Fuel,Carline Class Desc
0,2025,Aston Martin Lagonda Ltd,Vantage,4.0,8,15,22,18,R,Gasoline (Premium Unleaded Recommended),Two Seaters
1,2025,BMW,Z4 M40i,3.0,6,23,29,25,R,Gasoline (Premium Unleaded Recommended),Two Seaters
2,2025,BMW,Z4 M40i,3.0,6,19,26,22,R,Gasoline (Premium Unleaded Recommended),Two Seaters
3,2025,BMW,Z4 sDrive30i,2.0,4,25,33,28,R,Gasoline (Premium Unleaded Recommended),Two Seaters
4,2025,Bugatti,Mistral,8.0,16,8,12,9,A,Gasoline (Premium Unleaded Required),Two Seaters